name: 'Rerun Checks'

branding:
  icon: 'refresh-cw'
  color: 'purple'
description: 'Rerun specified GitHub checks'

inputs:
  check-names:
    description: 'Array of check names to rerun'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'